### PR TITLE
allow php-parser ~3.0

### PR DESCRIPTION
**Pull request by thewunder**
All unit tests pass for me in php 5.6, 7.0, and 7.1
I am guessing something is wrong with the travis config

### CODE REVIEW

**Comment by marcioAlmada** [comment]
It's probably their phpunit version.

Give this a try:

```
    "require-dev": {
        "phpunit/phpunit": "~5.2"
    }
```

It's ok for us to require phpunit as a dev dependency, from now on.

**Comment by thewunder** [comment]
Drop HHVM?

**Comment by thewunder** [comment]
Sweat, travis is happy now...

**Comment by marcioAlmada** [comment]
Thanks! I'm testing/merging/releasing ASAP.

**Comment by thewunder** [comment]
What are your plans to release?  Anything else I can help with?

The old php-parser version is preventing me from updating another package.

**Comment by marcioAlmada** [comment]
Done with [3.1.0](https://github.com/marcioAlmada/annotations/releases/tag/3.1.0).

**Pull request merged**
