### PR TITLE
Constant annotation

### PR DESCRIPTION
**Pull request by gsouf**
View #56 

I implemented constant annotation with https://github.com/nikic/PHP-Parser

- Test are written: https://github.com/marcioAlmada/annotations/compare/master...gsouf:master#diff-0bead099dbf66baa309e8061718a7defR70
- I added a class ReflectionConst that imeplements \Reflector in order to keep make it work with getAnnotations: https://github.com/gsouf/annotations/blob/918194f3d11bba3dcdfd95660bfd9c8441d01d79/src/Reader.php#L135

### CODE REVIEW

**Comment by marcioAlmada** [comment]
I'll do a final review later. This will be on v3 since it required altering a public interface. Thank you!

**Comment by gsouf** [comment]
Ok, I didnt notice that Reader implements ReaderInterface.

Without updating the interface, can we still publish this to the v2 without modifying the interface ? And then you update the interface in the v3 ? 
I need this feature and I'd like to be able to use it without some custom implementation.

**Comment by marcioAlmada** [comment]
That seems doable. Thanks!

**Comment by gsouf** [comment]
:+1:

**Pull request merged**
